[{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2882",
	"severity": 8,
	"message": "Cannot find module or type declarations for side-effect import of 'dotenv/config'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 23,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'express' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 21,
	"endLineNumber": 2,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'path'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 18,
	"endLineNumber": 3,
	"endColumn": 24,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'fs'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 16,
	"endLineNumber": 4,
	"endColumn": 20,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'bcryptjs' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 20,
	"endLineNumber": 5,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'vite' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 50,
	"endLineNumber": 6,
	"endColumn": 56,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module './server/database' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 7,
	"startColumn": 20,
	"endLineNumber": 7,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module './server/gemini' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 40,
	"endLineNumber": 8,
	"endColumn": 57,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module './src/types' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 26,
	"endLineNumber": 9,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module './src/db/postgres' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 19,
	"startColumn": 8,
	"endLineNumber": 19,
	"endColumn": 27,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 198,
	"startColumn": 12,
	"endLineNumber": 198,
	"endColumn": 15,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 198,
	"startColumn": 17,
	"endLineNumber": 198,
	"endColumn": 20,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'next' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 198,
	"startColumn": 22,
	"endLineNumber": 198,
	"endColumn": 26,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 27,
	"endLineNumber": 206,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 32,
	"endLineNumber": 206,
	"endColumn": 35,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 210,
	"startColumn": 24,
	"endLineNumber": 210,
	"endColumn": 27,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 210,
	"startColumn": 29,
	"endLineNumber": 210,
	"endColumn": 32,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 217,
	"startColumn": 12,
	"endLineNumber": 217,
	"endColumn": 15,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 217,
	"startColumn": 17,
	"endLineNumber": 217,
	"endColumn": 20,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'next' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 217,
	"startColumn": 22,
	"endLineNumber": 217,
	"endColumn": 26,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 254,
	"startColumn": 12,
	"endLineNumber": 254,
	"endColumn": 15,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 254,
	"startColumn": 17,
	"endLineNumber": 254,
	"endColumn": 20,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'next' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 254,
	"startColumn": 22,
	"endLineNumber": 254,
	"endColumn": 26,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 358,
	"startColumn": 12,
	"endLineNumber": 358,
	"endColumn": 15,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 358,
	"startColumn": 17,
	"endLineNumber": 358,
	"endColumn": 20,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'next' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 358,
	"startColumn": 22,
	"endLineNumber": 358,
	"endColumn": 26,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'r' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 362,
	"startColumn": 34,
	"endLineNumber": 362,
	"endColumn": 35,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 383,
	"startColumn": 28,
	"endLineNumber": 383,
	"endColumn": 31,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 383,
	"startColumn": 33,
	"endLineNumber": 383,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 405,
	"startColumn": 34,
	"endLineNumber": 405,
	"endColumn": 37,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 405,
	"startColumn": 39,
	"endLineNumber": 405,
	"endColumn": 42,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 410,
	"startColumn": 33,
	"endLineNumber": 410,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 410,
	"startColumn": 38,
	"endLineNumber": 410,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 441,
	"startColumn": 35,
	"endLineNumber": 441,
	"endColumn": 38,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 441,
	"startColumn": 40,
	"endLineNumber": 441,
	"endColumn": 43,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'm' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 445,
	"startColumn": 48,
	"endLineNumber": 445,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 462,
	"startColumn": 33,
	"endLineNumber": 462,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 462,
	"startColumn": 38,
	"endLineNumber": 462,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'p' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 466,
	"startColumn": 48,
	"endLineNumber": 466,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 487,
	"startColumn": 41,
	"endLineNumber": 487,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 487,
	"startColumn": 46,
	"endLineNumber": 487,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'm' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 503,
	"startColumn": 48,
	"endLineNumber": 503,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'p' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 504,
	"startColumn": 48,
	"endLineNumber": 504,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 526,
	"startColumn": 27,
	"endLineNumber": 526,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 526,
	"startColumn": 32,
	"endLineNumber": 526,
	"endColumn": 35,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 563,
	"startColumn": 32,
	"endLineNumber": 563,
	"endColumn": 35,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 563,
	"startColumn": 37,
	"endLineNumber": 563,
	"endColumn": 40,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 671,
	"startColumn": 35,
	"endLineNumber": 671,
	"endColumn": 38,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 671,
	"startColumn": 40,
	"endLineNumber": 671,
	"endColumn": 43,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 713,
	"startColumn": 38,
	"endLineNumber": 713,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 713,
	"startColumn": 43,
	"endLineNumber": 713,
	"endColumn": 46,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'u' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 715,
	"startColumn": 33,
	"endLineNumber": 715,
	"endColumn": 34,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 742,
	"startColumn": 33,
	"endLineNumber": 742,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 742,
	"startColumn": 38,
	"endLineNumber": 742,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 786,
	"startColumn": 33,
	"endLineNumber": 786,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 786,
	"startColumn": 38,
	"endLineNumber": 786,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 795,
	"startColumn": 42,
	"endLineNumber": 795,
	"endColumn": 45,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 795,
	"startColumn": 47,
	"endLineNumber": 795,
	"endColumn": 50,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 802,
	"startColumn": 50,
	"endLineNumber": 802,
	"endColumn": 53,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 802,
	"startColumn": 55,
	"endLineNumber": 802,
	"endColumn": 58,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 823,
	"startColumn": 51,
	"endLineNumber": 823,
	"endColumn": 54,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 823,
	"startColumn": 56,
	"endLineNumber": 823,
	"endColumn": 59,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 839,
	"startColumn": 52,
	"endLineNumber": 839,
	"endColumn": 55,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 839,
	"startColumn": 57,
	"endLineNumber": 839,
	"endColumn": 60,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 848,
	"startColumn": 49,
	"endLineNumber": 848,
	"endColumn": 52,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 848,
	"startColumn": 54,
	"endLineNumber": 848,
	"endColumn": 57,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 852,
	"startColumn": 36,
	"endLineNumber": 852,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 852,
	"startColumn": 41,
	"endLineNumber": 852,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 874,
	"startColumn": 52,
	"endLineNumber": 874,
	"endColumn": 55,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 874,
	"startColumn": 57,
	"endLineNumber": 874,
	"endColumn": 60,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 882,
	"startColumn": 59,
	"endLineNumber": 882,
	"endColumn": 62,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 882,
	"startColumn": 64,
	"endLineNumber": 882,
	"endColumn": 67,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 886,
	"startColumn": 88,
	"endLineNumber": 886,
	"endColumn": 91,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 886,
	"startColumn": 93,
	"endLineNumber": 886,
	"endColumn": 96,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 894,
	"startColumn": 54,
	"endLineNumber": 894,
	"endColumn": 57,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 894,
	"startColumn": 59,
	"endLineNumber": 894,
	"endColumn": 62,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 922,
	"startColumn": 57,
	"endLineNumber": 922,
	"endColumn": 60,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 922,
	"startColumn": 62,
	"endLineNumber": 922,
	"endColumn": 65,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 941,
	"startColumn": 55,
	"endLineNumber": 941,
	"endColumn": 58,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 941,
	"startColumn": 60,
	"endLineNumber": 941,
	"endColumn": 63,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 945,
	"startColumn": 55,
	"endLineNumber": 945,
	"endColumn": 58,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 945,
	"startColumn": 60,
	"endLineNumber": 945,
	"endColumn": 63,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 959,
	"startColumn": 61,
	"endLineNumber": 959,
	"endColumn": 64,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 959,
	"startColumn": 66,
	"endLineNumber": 959,
	"endColumn": 69,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 975,
	"startColumn": 56,
	"endLineNumber": 975,
	"endColumn": 59,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 975,
	"startColumn": 61,
	"endLineNumber": 975,
	"endColumn": 64,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 997,
	"startColumn": 66,
	"endLineNumber": 997,
	"endColumn": 69,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 997,
	"startColumn": 71,
	"endLineNumber": 997,
	"endColumn": 74,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1001,
	"startColumn": 67,
	"endLineNumber": 1001,
	"endColumn": 70,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1001,
	"startColumn": 72,
	"endLineNumber": 1001,
	"endColumn": 75,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1022,
	"startColumn": 70,
	"endLineNumber": 1022,
	"endColumn": 73,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1022,
	"startColumn": 75,
	"endLineNumber": 1022,
	"endColumn": 78,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1028,
	"startColumn": 73,
	"endLineNumber": 1028,
	"endColumn": 76,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1028,
	"startColumn": 78,
	"endLineNumber": 1028,
	"endColumn": 81,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1056,
	"startColumn": 40,
	"endLineNumber": 1056,
	"endColumn": 43,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1056,
	"startColumn": 45,
	"endLineNumber": 1056,
	"endColumn": 48,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1079,
	"startColumn": 54,
	"endLineNumber": 1079,
	"endColumn": 55,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1085,
	"startColumn": 88,
	"endLineNumber": 1085,
	"endColumn": 91,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1085,
	"startColumn": 93,
	"endLineNumber": 1085,
	"endColumn": 96,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1097,
	"startColumn": 25,
	"endLineNumber": 1097,
	"endColumn": 28,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1097,
	"startColumn": 30,
	"endLineNumber": 1097,
	"endColumn": 33,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1101,
	"startColumn": 36,
	"endLineNumber": 1101,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1101,
	"startColumn": 41,
	"endLineNumber": 1101,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1105,
	"startColumn": 86,
	"endLineNumber": 1105,
	"endColumn": 89,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1105,
	"startColumn": 91,
	"endLineNumber": 1105,
	"endColumn": 94,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1110,
	"startColumn": 89,
	"endLineNumber": 1110,
	"endColumn": 92,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1110,
	"startColumn": 94,
	"endLineNumber": 1110,
	"endColumn": 97,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 92,
	"endLineNumber": 1116,
	"endColumn": 95,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 97,
	"endLineNumber": 1116,
	"endColumn": 100,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1122,
	"startColumn": 31,
	"endLineNumber": 1122,
	"endColumn": 34,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1122,
	"startColumn": 36,
	"endLineNumber": 1122,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1128,
	"startColumn": 75,
	"endLineNumber": 1128,
	"endColumn": 78,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1128,
	"startColumn": 80,
	"endLineNumber": 1128,
	"endColumn": 83,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1133,
	"startColumn": 78,
	"endLineNumber": 1133,
	"endColumn": 81,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1133,
	"startColumn": 83,
	"endLineNumber": 1133,
	"endColumn": 86,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'm' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1134,
	"startColumn": 45,
	"endLineNumber": 1134,
	"endColumn": 46,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1151,
	"startColumn": 81,
	"endLineNumber": 1151,
	"endColumn": 84,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1151,
	"startColumn": 86,
	"endLineNumber": 1151,
	"endColumn": 89,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1161,
	"startColumn": 25,
	"endLineNumber": 1161,
	"endColumn": 28,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1161,
	"startColumn": 30,
	"endLineNumber": 1161,
	"endColumn": 33,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1165,
	"startColumn": 36,
	"endLineNumber": 1165,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1165,
	"startColumn": 41,
	"endLineNumber": 1165,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1169,
	"startColumn": 31,
	"endLineNumber": 1169,
	"endColumn": 34,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1169,
	"startColumn": 36,
	"endLineNumber": 1169,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1175,
	"startColumn": 91,
	"endLineNumber": 1175,
	"endColumn": 94,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1175,
	"startColumn": 96,
	"endLineNumber": 1175,
	"endColumn": 99,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'err' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1178,
	"startColumn": 37,
	"endLineNumber": 1178,
	"endColumn": 40,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1184,
	"startColumn": 94,
	"endLineNumber": 1184,
	"endColumn": 97,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1184,
	"startColumn": 99,
	"endLineNumber": 1184,
	"endColumn": 102,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'p' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1185,
	"startColumn": 45,
	"endLineNumber": 1185,
	"endColumn": 46,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'err' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1190,
	"startColumn": 37,
	"endLineNumber": 1190,
	"endColumn": 40,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1207,
	"startColumn": 87,
	"endLineNumber": 1207,
	"endColumn": 90,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1207,
	"startColumn": 92,
	"endLineNumber": 1207,
	"endColumn": 95,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'err' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1211,
	"startColumn": 47,
	"endLineNumber": 1211,
	"endColumn": 50,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1221,
	"startColumn": 33,
	"endLineNumber": 1221,
	"endColumn": 36,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1221,
	"startColumn": 38,
	"endLineNumber": 1221,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1225,
	"startColumn": 39,
	"endLineNumber": 1225,
	"endColumn": 42,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1225,
	"startColumn": 44,
	"endLineNumber": 1225,
	"endColumn": 47,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1231,
	"startColumn": 83,
	"endLineNumber": 1231,
	"endColumn": 86,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1231,
	"startColumn": 88,
	"endLineNumber": 1231,
	"endColumn": 91,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1236,
	"startColumn": 86,
	"endLineNumber": 1236,
	"endColumn": 89,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1236,
	"startColumn": 91,
	"endLineNumber": 1236,
	"endColumn": 94,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1242,
	"startColumn": 89,
	"endLineNumber": 1242,
	"endColumn": 92,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1242,
	"startColumn": 94,
	"endLineNumber": 1242,
	"endColumn": 97,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1253,
	"startColumn": 39,
	"endLineNumber": 1253,
	"endColumn": 42,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1253,
	"startColumn": 44,
	"endLineNumber": 1253,
	"endColumn": 47,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1265,
	"startColumn": 106,
	"endLineNumber": 1265,
	"endColumn": 109,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1265,
	"startColumn": 111,
	"endLineNumber": 1265,
	"endColumn": 114,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1276,
	"startColumn": 41,
	"endLineNumber": 1276,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1276,
	"startColumn": 46,
	"endLineNumber": 1276,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1280,
	"startColumn": 101,
	"endLineNumber": 1280,
	"endColumn": 104,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1280,
	"startColumn": 106,
	"endLineNumber": 1280,
	"endColumn": 109,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1285,
	"startColumn": 104,
	"endLineNumber": 1285,
	"endColumn": 107,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1285,
	"startColumn": 109,
	"endLineNumber": 1285,
	"endColumn": 112,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1291,
	"startColumn": 97,
	"endLineNumber": 1291,
	"endColumn": 100,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1291,
	"startColumn": 102,
	"endLineNumber": 1291,
	"endColumn": 105,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1298,
	"startColumn": 36,
	"endLineNumber": 1298,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1298,
	"startColumn": 41,
	"endLineNumber": 1298,
	"endColumn": 44,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1302,
	"startColumn": 86,
	"endLineNumber": 1302,
	"endColumn": 89,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1302,
	"startColumn": 91,
	"endLineNumber": 1302,
	"endColumn": 94,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1307,
	"startColumn": 89,
	"endLineNumber": 1307,
	"endColumn": 92,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1307,
	"startColumn": 94,
	"endLineNumber": 1307,
	"endColumn": 97,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1313,
	"startColumn": 92,
	"endLineNumber": 1313,
	"endColumn": 95,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1313,
	"startColumn": 97,
	"endLineNumber": 1313,
	"endColumn": 100,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1320,
	"startColumn": 34,
	"endLineNumber": 1320,
	"endColumn": 37,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1320,
	"startColumn": 39,
	"endLineNumber": 1320,
	"endColumn": 42,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1324,
	"startColumn": 84,
	"endLineNumber": 1324,
	"endColumn": 87,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1324,
	"startColumn": 89,
	"endLineNumber": 1324,
	"endColumn": 92,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1329,
	"startColumn": 87,
	"endLineNumber": 1329,
	"endColumn": 90,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1329,
	"startColumn": 92,
	"endLineNumber": 1329,
	"endColumn": 95,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1335,
	"startColumn": 90,
	"endLineNumber": 1335,
	"endColumn": 93,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1335,
	"startColumn": 95,
	"endLineNumber": 1335,
	"endColumn": 98,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1342,
	"startColumn": 30,
	"endLineNumber": 1342,
	"endColumn": 33,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1342,
	"startColumn": 35,
	"endLineNumber": 1342,
	"endColumn": 38,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1346,
	"startColumn": 80,
	"endLineNumber": 1346,
	"endColumn": 83,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1346,
	"startColumn": 85,
	"endLineNumber": 1346,
	"endColumn": 88,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1351,
	"startColumn": 83,
	"endLineNumber": 1351,
	"endColumn": 86,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1351,
	"startColumn": 88,
	"endLineNumber": 1351,
	"endColumn": 91,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1357,
	"startColumn": 86,
	"endLineNumber": 1357,
	"endColumn": 89,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1357,
	"startColumn": 91,
	"endLineNumber": 1357,
	"endColumn": 94,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1364,
	"startColumn": 34,
	"endLineNumber": 1364,
	"endColumn": 37,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1364,
	"startColumn": 39,
	"endLineNumber": 1364,
	"endColumn": 42,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1369,
	"startColumn": 56,
	"endLineNumber": 1369,
	"endColumn": 59,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1369,
	"startColumn": 61,
	"endLineNumber": 1369,
	"endColumn": 64,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1380,
	"startColumn": 42,
	"endLineNumber": 1380,
	"endColumn": 45,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1380,
	"startColumn": 47,
	"endLineNumber": 1380,
	"endColumn": 50,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 1446,
	"startColumn": 30,
	"endLineNumber": 1446,
	"endColumn": 37,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 1448,
	"startColumn": 17,
	"endLineNumber": 1448,
	"endColumn": 24,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 1448,
	"startColumn": 72,
	"endLineNumber": 1448,
	"endColumn": 79,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1530,
	"startColumn": 25,
	"endLineNumber": 1530,
	"endColumn": 28,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1530,
	"startColumn": 30,
	"endLineNumber": 1530,
	"endColumn": 33,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'next' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1530,
	"startColumn": 35,
	"endLineNumber": 1530,
	"endColumn": 39,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "2591",
	"severity": 8,
	"message": "Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.",
	"source": "ts",
	"startLineNumber": 1535,
	"startColumn": 55,
	"endLineNumber": 1535,
	"endColumn": 62,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1547,
	"startColumn": 19,
	"endLineNumber": 1547,
	"endColumn": 22,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1547,
	"startColumn": 24,
	"endLineNumber": 1547,
	"endColumn": 27,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'ok' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1569,
	"startColumn": 36,
	"endLineNumber": 1569,
	"endColumn": 38,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'p' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1576,
	"startColumn": 53,
	"endLineNumber": 1576,
	"endColumn": 54,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/MAHER ALYAN/Untitled-1.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'err' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1594,
	"startColumn": 13,
	"endLineNumber": 1594,
	"endColumn": 16,
	"modelVersionId": 2,
	"origin": "extHost1"
}]
